services:
  memoana:
    image: ${DOCKER_REGISTRY-}memoana
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    volumes:
      - memoana_data:/data
    networks:
      - tunnel

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    env_file:
        - .env 
    restart: unless-stopped
    depends_on:
      - memoana
    networks:
      - tunnel

volumes:
  memoana_app:
    driver: local
  memoana_data:
    driver: local

networks:
  tunnel:
    name: tunnel